#!/bin/bash

# CLEAN BUILD
Eclipse.app/Contents/MacOS/eclipse --nosplash --launcher.suppressErrors -application org.eclipse.jdt.apt.core.aptBuild -data "/Users/andrewlee/Documents/workspace"

echo "
*****************************
SwingJS- Clean Build Complete
*****************************
"
ant -buildfile ~/git/SwingJS/buildSite.xml
