#!/bin/bash

# Download
BINARY = "eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz"
APP = "Eclipse.app"
if [! -d $APP ]; then
    rm -rf Eclipse.app
    if [! -f $BINARY ]; then
        brew install unzip
        tar xvf eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        rm eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        unzip 3.1.1.zip
        mv net.sf.j2s.core_3.1.1.jar Eclipse.app/Contents/Eclipse/dropins/net.sf.j2s.core_3.1.1.jar
        rm *.jar
        rm -rf net.sf.j2s.ajax_3.1.1
        rm -rf net.sf.j2s.lib_3.1.1
        rm 3.1.1.zip
    else
        brew install unzip
        wget https://github.com/BobHanson/java2script/releases/download/v3.1.1/3.1.1.zip
        wget http://eclipse.mirror.rafal.ca/technology/epp/downloads/release/neon/3/eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        tar xvf eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        rm eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        unzip 3.1.1.zip
        mv net.sf.j2s.core_3.1.1.jar Eclipse.app/Contents/Eclipse/dropins/net.sf.j2s.core_3.1.1.jar
        rm *.jar
        rm -rf net.sf.j2s.ajax_3.1.1
        rm -rf net.sf.j2s.lib_3.1.1
        rm 3.1.1.zip
    fi
else
    if [! -f $BINARY ]; then
        brew install unzip
        wget https://github.com/BobHanson/java2script/releases/download/v3.1.1/3.1.1.zip
        tar xvf eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        rm eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        unzip 3.1.1.zip
        mv net.sf.j2s.core_3.1.1.jar Eclipse.app/Contents/Eclipse/dropins/net.sf.j2s.core_3.1.1.jar
        rm *.jar
        rm -rf net.sf.j2s.ajax_3.1.1
        rm -rf net.sf.j2s.lib_3.1.1
        rm 3.1.1.zip
    else
        brew install unzip
        wget https://github.com/BobHanson/java2script/releases/download/v3.1.1/3.1.1.zip
        wget http://eclipse.mirror.rafal.ca/technology/epp/downloads/release/neon/3/eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        tar xvf eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        rm eclipse-jee-neon-3-macosx-cocoa-x86_64.tar.gz
        unzip 3.1.1.zip
        mv net.sf.j2s.core_3.1.1.jar Eclipse.app/Contents/Eclipse/dropins/net.sf.j2s.core_3.1.1.jar
        rm *.jar
        rm -rf net.sf.j2s.ajax_3.1.1
        rm -rf net.sf.j2s.lib_3.1.1
        rm 3.1.1.zip
    fi
fi
